FROM postgres

#psql --command "CREATE USER pronto WITH SUPERUSER PASSWORD 'pronto';" &&\
#RUN    /etc/init.d/postgresql start
#    psql --command "CREATE USER pronto_usr WITH PASSWORD 'pronto';" &&\
#    createdb --owner=pronto prontoDB